apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_DB            
              key: dft
            - name: POSTGRES_USER
              key: myuser
            - name: POSTGRES_PASSWORD
              key: rty_12345
          ports:
            - containerPort: 5432
          volumeMounts: 
            - mountPath: /var/lib/postgresql/data
              name: {{ include "postgresql.fullname" . }}
              subPath: postgres
          resources:
            {{- toYaml .Values.resources | nindent 12 }}      
      volumes:
        - name: {{ include "postgresql.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "postgresql.fullname" . }}
