version: "3.2"
services: 
  db:
    image: postgres
    restart: always
    network_mode: host
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: user

  webapp:
    image: 460700981334.dkr.ecr.eu-central-1.amazonaws.com/dft-ui:latest
    ports:
      - "3000:80"

  rest-api:
    depends_on:      
      - db
    image: 460700981334.dkr.ecr.eu-central-1.amazonaws.com/dft-api:5fc3290d38403674cb54cd95b778ce6c88845fbf
    network_mode: host
    ports:
      - "8080:8080"