apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MANUFACTURERID
              value: "catenaX"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: dft-postgres-secrets
                  key: dbUrl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dft-postgres-secrets
                  key: dbUser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dft-postgres-secrets
                  key: dbPassword
            - name: DIGITAL-TWINS_URL
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinUrl
            - name: DIGITAL-TWINS_AUTHENTICATION_URL
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinAuthorizationUrl
            - name: DIGITAL-TWINS_AUTHENTICATION_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinAuthorizationClientId
            - name: DIGITAL-TWINS_AUTHENTICATION_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinAuthorizationClientSecret
            - name: EDC_ASPECT_URL
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcAspectUrl
            - name: EDC_ASPECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcAspectApiKey
            - name: EDC_ASPECT_API_VALUE
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcAspectApiValue
            - name: EDC_CHILD_ASPECT_URL
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcChildAspectUrl
            - name: EDC_CHILD_ASPECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcChildAspectApiKey
            - name: EDC_CHILD_ASPECT_API_VALUE
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcChildAspectApiValue
            - name: EDC_ASSET_PAYLOAD_URL
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcAssetPayloadUrl
            - name: EDC_ASSET_RELATIONSHIP_PAYLOAD_URL
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcAssetRelationshipPayloadUrl
            - name: EDC_ASSET_PAYLOAD_URL_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcAssetPayloadUrlAuthKey
            - name: EDC_ASSET_PAYLOAD_URL_AUTH_CODE
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcAssetPayloadUrlAuthCode
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.endpoint }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.endpoint }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
