apiVersion: v1
kind: Secret
metadata:
  name: dtf-digitaltwins-secrets
  annotations:
    avp.kubernetes.io/path: "dft/data/digital-twins"
    avp.kubernetes.io/secret-version: "5"
type: Opaque
stringData:
  digitalTwinHostname: <hostname>
  digitalTwinAuthorizationUrl: <authentication-url>
  digitalTwinAuthorizationClientId: <authentication-clientId>
  digitalTwinAuthorizationClientSecret: <authentication-clientSecret>
