apiVersion: v1
kind: Secret
metadata:
  name: dtf-postgres-secrets
  annotations:
    avp.kubernetes.io/path: "dft/data/postgres"
    avp.kubernetes.io/secret-version: "7"
type: Opaque
stringData:
  dbpassword: <DB_PASSWORD>
  dbuser: <DB_USERNAME>