apiVersion: v1
kind: Secret
metadata:
  name: dtf-digitaltwins-secrets
  annotations:
    avp.kubernetes.io/path: "dft/data/digital-twins"
type: Opaque
stringData:
  digitalTwinUrl: <url>
  digitalTwinAuthorizationUrl: <authentication-url>
  digitalTwinAuthorizationClientId: <authentication-clientId>
  digitalTwinAuthorizationClientSecret: <authentication-clientSecret>
