{{- if .Values.ingress.enabled -}}
{{- $fullName := include "omejdn-server.fullname" . -}}
{{- $ingressExtraPaths := .Values.ingress.extraPaths -}}
{{- $svcName := include "omejdn-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
     {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
   {{- toYaml . | nindent 4 }}
 {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
       - {{ .Values.ingress.host }}
      secretName: {{ include "helm.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}


