apiVersion: v1
kind: Secret
metadata:
  name: dft-postgresql-secrets
  #namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  dbUrl: {{ .Values.postgres.secret.url | default ( randAlphaNum 32 | quote ) }}
  dbUser: {{ .Values.postgres.secret.user | default ( randAlphaNum 32 | quote ) }}
  dbPassword: {{ .Values.postgres.secret.password | default ( randAlphaNum 32 | quote )}}
  postgres-password: {{ .Values.postgresql.secret.password | default ( randAlphaNum 32 | quote ) }}
