apiVersion: v1
kind: Secret
metadata:
  name: dft-postgresql-secrets
  #namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  dbUrl: {{ .Values.postgres.secret.url | b64enc }}
  dbUser: {{ .Values.postgres.secret.user | b64enc }}
  dbPassword: {{ .Values.postgres.secret.password | b64enc }}
