apiVersion: v1
kind: Secret
metadata:
  name: dft-postgresql-secrets
type: Opaque
stringData:
  username: {{ .Values.dftpostgresql.auth.username | default ( "dftuser" ) }}
  password: {{ .Values.dftpostgresql.auth.password | default ( randAlphaNum 32 | quote ) }}
  postgresPassword: {{ .Values.dftpostgresql.auth.postgresPassword | default ( randAlphaNum 32 | quote ) }}