apiVersion: v1
kind: Secret
metadata:
  name: dft-postgresql-secrets
type: Opaque
stringData:
  password: {{ .Values.dftpostgresql.auth.password | default ( randAlphaNum 32 | quote ) }}
  postgresPassword: {{ .Values.dftpostgresql.auth.postgresPassword | default ( randAlphaNum 32 | quote ) }}