apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-backend
spec:
  destination:
    namespace: product-portal
    server: 'https://kubernetes.default.svc'
  source:
    path: chart/portal-backend
    repoURL: 'https://github.com/catenax-ng/product-dft-backend.git'
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml'
  project: project-portal