apiVersion: v1
kind: Secret
metadata:
  name: dft-postgres-secrets
  annotations:
    avp.kubernetes.io/path: "dft/data/postgres"
    avp.kubernetes.io/secret-version: "9"
type: Opaque
stringData:
  dbUrl: <DB_URL>
  dbUser: <DB_USERNAME>
  dbPassword: <DB_PASSWORD>
