apiVersion: v1
entries:
  dftbe:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-17T20:05:41.428244+05:30"
    description: A Helm chart for Kubernetes
    digest: b1f9b18c96e4b965c1b9046a28297e7c35b9c6f1f1ec16c2f665d5fc5de41c4f
    name: dftbe
    type: application
    urls:
    - https://catenax-ng.github.io/product-dft-backend/deployment/helm/dftbe-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-17T20:05:41.427504+05:30"
