apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.dbSecretName}}
type: Opaque
stringData:
  dbuser: "<path:dft/data/edc#DB_USER>"
  postgres-password: "<path:dft/data/edc#DB_PASSWORD>"
  password: "<path:dft/data/edc#DB_PASSWORD>"
  dburl: "<path:dft/data/edcs#DB_URL>"
  dbname: "<path:dft/data/edcs#DB_NAME>"
